import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import { SessionProvider } from "next-auth/react";
import type { Session } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: // pageProps: { session, ...pageProps },
{
	children: React.ReactNode;
	// pageProps: { session: Session | null | undefined };
}) {
	return (
		// <SessionProvider session={session ?? null}>
		<html lang="en">
			<body className={inter.className}>
				<NavigationBar />
				{children}
			</body>
		</html>
		// </SessionProvider>
	);
}
